apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: your_password
  DB_NAME: your_database
  DB_HOST: your_postgres_host
  DB_PORT: "5432"
  SECRET_KEY: your_secret_key
  JWT_SECRET_KEY: your_jwt_secret
